steps:
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  args:
  - gcloud
  - functions
  - deploy
  - load_cards
  - --region=us_central1
  - --trigger-topic=load_cards
  - --runtime=python311
  dir: 'functions/load_cards'