steps:
- name: python
  entrypoint: pip
  args:
  - install
  - -r
  - requirements.txt
  - --user
  dir: 'functions/load_cards'

- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  args:
  - gcloud
  - functions
  - deploy
  - load_cards
  - --region=us-east1
  - --trigger-topic=load_cards
  - --runtime=python311
  - --gen2
  - --set-secrets=BEARER_TOKEN=givecard_dev_token:latest
  dir: 'functions/load_cards'