steps:
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    args:
    - gcloud
    - functions
    - deploy
    - load_cards
    - --region=us_east1
    - --source=./functions/load_cards/main.py
    - --trigger-topic=load_cards
    - --runtime=python311